os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10.0"
jdk:
  - oraclejdk8
cache:
  directories:
    - node_modules
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/app/node_modules
    - $HOME/app/node
env:
  global:
    - PROFILE=dev
    - RUN_APP=1
    - PROTRACTOR=0
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
  matrix:
    - JHIPSTER=app-default-from-scratch JHIPSTER_NODE_CACHE=0 PROFILE=prod RUN_APP=0
    - JHIPSTER=app-gradle PROTRACTOR=1
    - JHIPSTER=app-mysql PROFILE=prod PROTRACTOR=1
    - JHIPSTER=app-psql-es-noi18n PROFILE=prod PROTRACTOR=1
    - JHIPSTER=app-gateway
before_install:
  - sudo /etc/init.d/postgresql stop
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod +x $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
  - chmod +x $JHIPSTER_INSTALL/03-checkVersion.sh
  - chmod +x $JHIPSTER_INSTALL/04-cache.sh
install:
  - $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
  - $JHIPSTER_INSTALL/03-checkVersion.sh
  - $JHIPSTER_INSTALL/04-cache.sh
before_script:
  - chmod +x $JHIPSTER_SCRIPTS/01-generate-project.sh
  - chmod +x $JHIPSTER_SCRIPTS/02-generate-entities.sh
  - chmod +x $JHIPSTER_SCRIPTS/03-generate-audit.sh
  - chmod +x $JHIPSTER_SCRIPTS/04-tests.sh
  - chmod +x $JHIPSTER_SCRIPTS/05-run.sh
script:
  - $JHIPSTER_SCRIPTS/01-generate-project.sh
  - $JHIPSTER_SCRIPTS/02-generate-entities.sh
  - $JHIPSTER_SCRIPTS/03-generate-audit.sh
  - $JHIPSTER_SCRIPTS/04-tests.sh
  - $JHIPSTER_SCRIPTS/05-run.sh
