os:
    - linux
services:
    - docker
language:
    - node_js
node_js:
    - "6.10.0"
jdk:
    - oraclejdk8
cache:
  directories:
    - node_modules
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/app/node_modules
    - $HOME/app/node
env:
    global:
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
install:
    - $JHIPSTER_INSTALL/install-jhipster-stack.sh
